version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    reviewers:
      - nimdanitro
    schedule:
      interval: "daily"
      time: "20:00"
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        dependency-type: "development"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      fontawesome:
        applies-to: version-updates
        patterns:
          - "@fortawesome*"     
    labels:
      - "javascript"
      - "dependencies"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    reviewers:
      - nimdanitro
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "dependencies"
      
  # Enable version updates for Github Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - nimdanitro
    schedule:
      interval: "daily"
      time: "20:00"
    labels:
      - "gh-actions"
      - "dependencies"
