name: Automated Tests and Linting

on: [push]

jobs:
  Test:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: yarn
          cache-dependency-path: "yarn.lock"
      - name: Install packages
        run: yarn install --immutable
      - name: Run tests
        run: yarn test
